%%{init: {"flowchart": {"curve": "linear"}} }%%
graph TD
  __start__([__start__]):::first
  route(route)
  rag(rag)
  general(general)
  refund_extract(refund_extract)
  refund(refund)
  complaint_extract(complaint_extract)
  complaint(complaint)
  handoff(handoff)
  __end__([__end__]):::last

  __start__ --> route
  route -. complaint .-> complaint_extract
  route -. general .-> rag
  route -. refund .-> refund_extract
  route -.-> handoff

  rag --> general
  refund_extract --> refund
  complaint_extract --> complaint

  complaint --> __end__
  general --> __end__
  handoff --> __end__
  refund --> __end__

  classDef default fill:#f2f0ff,line-height:1.2
  classDef first fill-opacity:0
  classDef last fill:#bfb6fc
