#!/usr/bin/env python3
"""

This script is generated by perplexity to quickly feed the data
Seed the Kirana Ghar API with Indian shop owners, customers, shops and products.

Usage:
  python scripts/seed_sample_data.py \
    --api http://localhost:8000 \
    --owners 8 \
    --customers 20 \
    --shops-per-owner 2 4 \
    --products-per-shop 6 12

Notes:
  - Requires Python 3.8+ and the 'requests' package: pip install requests
  - The backend must be running and accessible at --api
  - The script is idempotent-ish for users: if a username already exists, it
    logs and continues. Shops/products will be added on every run for users
    that can authenticate.
"""

from __future__ import annotations

import argparse
import random
import string
import sys
import time
from dataclasses import dataclass

import requests


def rupees(low: int, high: int) -> float:
    return float(random.randint(low, high))


INDIAN_FIRST_NAMES = [
    "Aarav",
    "Vivaan",
    "Aditya",
    "Vihaan",
    "Krishna",
    "Arjun",
    "Sai",
    "Reyansh",
    "Mohammed",
    "Atharv",
    "Ananya",
    "Aadhya",
    "Aarohi",
    "Saanvi",
    "Diya",
    "Ira",
    "Myra",
    "Anika",
    "Navya",
    "Aarya",
]

INDIAN_LAST_NAMES = [
    "Sharma",
    "Verma",
    "Gupta",
    "Iyer",
    "Nair",
    "Patel",
    "Singh",
    "Yadav",
    "Khan",
    "Reddy",
    "Das",
    "Chatterjee",
    "Mukherjee",
    "Banerjee",
    "Mehta",
    "Kulkarni",
    "Pillai",
    "Shetty",
    "Jain",
    "Sinha",
]

INDIAN_CITIES = [
    "Mumbai",
    "Delhi",
    "Bengaluru",
    "Chennai",
    "Kolkata",
    "Hyderabad",
    "Pune",
    "Jaipur",
    "Chandigarh",
    "Ahmedabad",
    "Surat",
    "Lucknow",
    "Indore",
]

SHOP_NAME_PARTS = [
    "Annapurna",
    "Lakshmi",
    "Siddhi Vinayak",
    "Kirana",
    "Ration Point",
    "Desi Bazar",
    "Fresh Mart",
    "Supermart",
    "General Stores",
    "Daily Needs",
]

GROCERY_PRODUCTS = [
    "Atta (Wheat Flour)",
    "Basmati Rice",
    "Tur Dal",
    "Moong Dal",
    "Chana Dal",
    "Sugar",
    "Salt",
    "Mustard Oil",
    "Refined Oil",
    "Ghee",
    "Poha",
    "Suji (Rava)",
    "Besan",
    "Jaggery (Gur)",
    "Masala (Garam Masala)",
    "Turmeric Powder",
    "Red Chilli Powder",
    "Coriander Powder",
    "Jeera",
    "Tea",
    "Coffee",
    "Biscuits",
]


def gen_mobile() -> str:
    # Indian 10-digit starting with 9/8/7
    start = random.choice(["9", "8", "7"])
    return start + "".join(random.choice(string.digits) for _ in range(9))


def address_for(city: str) -> str:
    return f"House {random.randint(10, 250)}, Sector {random.randint(1, 50)}, {city} - {random.randint(110000, 499999)}"


def username_for(first: str, last: str) -> str:
    suffix = random.randint(10, 99)
    return f"{first.lower()}{last.lower()[0]}{suffix}"


def request_json(method: str, url: str, **kwargs):
    resp = requests.request(method, url, timeout=15, **kwargs)
    try:
        data = resp.json()
    except Exception:
        data = None
    return resp, data


def register_user(api: str, role: str, first: str, last: str) -> tuple[str | None, bool]:
    username = username_for(first, last)
    payload = {
        "username": username,
        "password": "Pass@1234",
        "role": role,
        "full_name": f"{first} {last}",
        "address": address_for(random.choice(INDIAN_CITIES)),
        "mobile": gen_mobile(),
    }
    r, data = request_json("POST", f"{api}/register", json=payload)
    if r.status_code == 201:
        print(f"✓ Registered {role}: {username}")
        return username, True
    if r.status_code == 400 and data and isinstance(data, dict) and data.get("detail") == "Username already taken":
        print(f"• {role} {username} already exists")
        return username, False
    print(f"! Failed registering {role} {username}: {r.status_code} {data}")
    return None, False


def login(api: str, username: str, password: str) -> str | None:
    r, data = request_json(
        "POST",
        f"{api}/token",
        data={"username": username, "password": password},
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    if r.ok and data and data.get("access_token"):
        return data["access_token"]
    print(f"! Login failed for {username}: {r.status_code} {data}")
    return None


def create_shop(api: str, token: str, name: str, city: str) -> str | None:
    r, data = request_json(
        "POST",
        f"{api}/shops/",
        data={"name": name, "city": city},
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/x-www-form-urlencoded",
        },
    )
    if r.ok and data and data.get("id"):
        return data["id"]
    print(f"! Create shop failed: {r.status_code} {data}")
    return None


def add_product(api: str, token: str, shop_id: str, name: str, price: float) -> bool:
    r, data = request_json(
        "POST",
        f"{api}/shops/{shop_id}/products/",
        json={"name": name, "price": price},
        headers={"Authorization": f"Bearer {token}"},
    )
    if r.status_code == 201:
        return True
    print(f"! Add product failed: {r.status_code} {data}")
    return False


def random_shop_name() -> str:
    return f"{random.choice(SHOP_NAME_PARTS)} {random.choice(['Stores','Kirana','Bhandar','Bazaar','Mart'])}"


def main():
    parser = argparse.ArgumentParser(description="Seed Kirana Ghar demo data")
    parser.add_argument("--api", default="http://localhost:8000", help="Base API URL")
    parser.add_argument("--owners", type=int, default=6, help="Number of shop owners")
    parser.add_argument("--customers", type=int, default=12, help="Number of customers")
    parser.add_argument("--shops-per-owner", nargs=2, type=int, metavar=("MIN", "MAX"), default=(1, 3))
    parser.add_argument("--products-per-shop", nargs=2, type=int, metavar=("MIN", "MAX"), default=(6, 10))
    args = parser.parse_args()

    api = args.api.rstrip("/")

    random.seed(42)

    # 1) Register owners and create shops + products
    for i in range(args.owners):
        first = random.choice(INDIAN_FIRST_NAMES)
        last = random.choice(INDIAN_LAST_NAMES)
        username, _ = register_user(api, "shopowner", first, last)
        if not username:
            continue
        token = login(api, username, "Pass@1234")
        if not token:
            continue

        nshops = random.randint(*args.shops_per_owner)
        for _ in range(nshops):
            city = random.choice(INDIAN_CITIES)
            shop_name = random_shop_name()
            shop_id = create_shop(api, token, shop_name, city)
            if not shop_id:
                continue
            nprod = random.randint(*args.products_per_shop)
            for name in random.sample(GROCERY_PRODUCTS, k=min(nprod, len(GROCERY_PRODUCTS))):
                price = rupees(20, 500)
                add_product(api, token, shop_id, name, price)

        time.sleep(0.2)

    # 2) Register customers
    for i in range(args.customers):
        first = random.choice(INDIAN_FIRST_NAMES)
        last = random.choice(INDIAN_LAST_NAMES)
        register_user(api, "customer", first, last)
        time.sleep(0.05)

    print("\nSeeding complete. You can now log in and browse.")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(130)

